version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atlas_ai_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - PORT=5000
      - FLASK_RUN_HOST=0.0.0.0
